# Generated by Django 3.1.1 on 2020-09-03 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plumbing', '0006_auto_20200903_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='maker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maker_field', to='plumbing.company'),
        ),
    ]
