# Generated by Django 3.1.1 on 2020-09-07 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plumbing', '0011_auto_20200904_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.URLField(default=None, max_length=300),
            preserve_default=False,
        ),
    ]
