# Generated by Django 3.1.1 on 2020-09-15 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plumbing', '0016_basket'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='send_data_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
