# Generated by Django 3.1.1 on 2020-09-18 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plumbing', '0019_productinstance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='count',
        ),
    ]
