# Generated by Django 3.1.1 on 2020-09-21 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plumbing', '0021_auto_20200921_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('n', 'Not confirmed'), ('c', 'Confirmed'), ('s', 'Submitted'), ('r', 'Received')], default='n', max_length=1),
        ),
    ]
