# Generated by Django 3.1.1 on 2020-09-21 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plumbing', '0022_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinstance',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='product_name',
            field=models.CharField(default='qwe', max_length=150),
            preserve_default=False,
        ),
    ]
